[package]
name = "rust-classicube-chatsounds-plugin"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
arrayvec = "0.5.0"
chatsounds = { path = "../rust-chatsounds" }
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
crossbeam-channel = "0.3.9"
detour = "0.7.1"
lazy_static = "1.4.0"
parking_lot = "0.9.0"
rand = "0.7.2"
winapi = { version = "0.3.8", features = ["winuser"] }
