[package]
name = "rust-classicube-chatsounds-plugin"
version = "1.0.2"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
arrayvec = "0.5.1"
async-std = "0.99.10"
chatsounds = { git = "https://github.com/SpiralP/rust-chatsounds.git" }
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
color-backtrace = { git = "https://github.com/SpiralP/color-backtrace-msgbox.git" }
crossbeam-channel = "0.3.9"
detour = "0.7.1"
futures-preview = { version = "0.3.0-alpha.19", features = ["async-await"] }
lazy_static = "1.4.0"
parking_lot = "0.9.0"
rand = "0.7.2"
rand_chacha = "0.2.1"
tokio = "0.2.0-alpha.6"
