[package]
name = "classicube-chatsounds-plugin"
version = "3.5.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
chatsounds = { git = "https://github.com/SpiralP/rust-chatsounds.git" }
classicube-helpers = { git = "https://github.com/SpiralP/rust-classicube-helpers.git", features = ["futures"] }
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
color-backtrace = { git = "https://github.com/SpiralP/color-backtrace-msgbox.git" }
crossbeam-channel = "0.4.2"
env_logger = "0.7.1"
futures = "0.3.5"
lazy_static = "1.4.0"
log = "0.4.8"
parking_lot = "0.10.2"
rand = "0.7.3"
rand_chacha = "0.2.2"
tokio = { version = "0.2.21", features = ["full"] }
