[package]
name = "rust-classicube-plugin"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
chatsounds = { path = "../rust-chatsounds" }
classicube = { path = "../rust-classicube" }
winapi = { version = "0.3.8", features = ["winuser"] }
