[package]
name = "classicube-chatsounds-plugin"
version = "3.6.3-alpha"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
chatsounds = { git = "https://github.com/SpiralP/rust-chatsounds.git" }
classicube-helpers = { git = "https://github.com/SpiralP/rust-classicube-helpers.git", features = ["futures"] }
classicube-sys = { git = "https://github.com/SpiralP/rust-classicube-sys.git" }
color-backtrace = { git = "https://github.com/SpiralP/color-backtrace-msgbox.git" }
crossbeam-channel = "0.5"
futures = "0.3"
lazy_static = "1"
parking_lot = "0.11"
rand = "0.8"
rand_chacha = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"


[package.metadata.release]
disable-publish = true
tag-message = "Release version {{version}}"
pre-release-commit-message = "Release {{version}}"
post-release-commit-message = "Begin {{next_version}}"
dev-version-ext = "alpha"
